assert 3 > 4
# 当结果为False时，则自动崩溃
# 抛出AssertionError的异常